apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-test
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-test
    spec:
      containers:
      - image: 347880001135.dkr.ecr.ap-northeast-2.amazonaws.com/test:1.0
        imagePullPolicy: Always
        name: app-test
        ports:
        - containerPort: 80